build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-github-release
    when:
      branch: master

plugin:
  name: GitHub Release
  desc: Publish files and artifacts to GitHub releases
  type: publish
  image: plugins/drone-github-release
  labels:
    - publish
    - github
    - release
