workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-github-release

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: plugins/docker
    repo: plugins/github-release
    tags: [ "latest", "1.0", "1" ]
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: push
